name: pln_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path: ^1.8.3
  path_provider: ^2.0.15
  http: ^1.1.0
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  logger: ^2.7.0
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.1.0
  geolocator: ^10.0.1
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/plnLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/plnLogo.svg
    - assets/plnLogo.png
